apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: fern-platform
  namespace: fern-platform
spec:
  components:
    # Fern Platform Service
    - name: fern-platform
      type: webservice
      properties:
        image: fern-platform:latest
        imagePullPolicy: Never  # For local development
        ports:
          - port: 8080
            expose: true
        env:
          - name: DB_HOST
            value: postgres-standalone
          - name: DB_PORT
            value: "5432"
          - name: DB_USER
            value: fern_user
          - name: DB_PASSWORD
            value: fern_password
          - name: DB_NAME
            value: fern_platform
          - name: LOG_LEVEL
            value: debug
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5

  policies:
    # Topology policy for local development
    - name: local-cluster
      type: topology
      properties:
        clusters: ["local"]
        namespace: fern-platform

  workflow:
    steps:
      # Step 1: Deploy application (PostgreSQL is deployed separately)
      - name: deploy-app
        type: deploy
        properties:
          policies: ["local-cluster"]
          auto: true

---
apiVersion: v1
kind: Namespace
metadata:
  name: fern-platform