# Local Development Configuration Patch
# Apply this after deploying the main application to fix OAuth URLs for local development
#
# Usage: kubectl apply -f local-dev-patch.yaml -n fern-platform

apiVersion: v1
kind: ConfigMap
metadata:
  name: fern-platform-oauth-config
  namespace: fern-platform
data:
  # For local development, we need different URLs for browser vs server-side requests
  # Browser needs to use the external URL (via Traefik ingress)
  OAUTH_AUTH_URL: "http://keycloak.fern-platform.local:8080/realms/fern-platform/protocol/openid-connect/auth"
  
  # Server-side URLs can use either internal service names or external URLs
  # Using external URLs for consistency in local dev
  OAUTH_TOKEN_URL: "http://keycloak.fern-platform.local:8080/realms/fern-platform/protocol/openid-connect/token"
  OAUTH_USERINFO_URL: "http://keycloak.fern-platform.local:8080/realms/fern-platform/protocol/openid-connect/userinfo"
  OAUTH_JWKS_URL: "http://keycloak.fern-platform.local:8080/realms/fern-platform/protocol/openid-connect/certs"
  OAUTH_ISSUER_URL: "http://keycloak.fern-platform.local:8080/realms/fern-platform"
  OAUTH_LOGOUT_URL: "http://keycloak.fern-platform.local:8080/realms/fern-platform/protocol/openid-connect/logout"

---
# Patch the deployment to use the ConfigMap
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fern-platform
  namespace: fern-platform
spec:
  template:
    spec:
      containers:
      - name: fern-platform
        envFrom:
        - configMapRef:
            name: fern-platform-oauth-config