# SLSA GoReleaser configuration
# Used by slsa-github-generator for reproducible builds

version: 1

# The main package
main: ./cmd/fern-platform

env:
  - CGO_ENABLED=0

flags:
  - -trimpath
  - -tags=netgo

# SLSA builds use environment variables from the matrix
# These are evaluated by the SLSA builder, not as Go templates
goos: "$GOOS"
goarch: "$GOARCH"

# Simplified binary name without ARM version suffix
binary: fern-platform-$GOOS-$GOARCH

ldflags:
  - "-s -w"
  - "-X github.com/guidewire-oss/fern-platform/pkg/config.Version={{ .Env.VERSION }}"
  - "-X github.com/guidewire-oss/fern-platform/pkg/config.Commit={{ .Env.COMMIT }}"
  - "-X github.com/guidewire-oss/fern-platform/pkg/config.CommitDate={{ .Env.COMMIT_DATE }}"
  - "-X github.com/guidewire-oss/fern-platform/pkg/config.TreeState={{ .Env.TREE_STATE }}"