name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    
    - name: Generate GraphQL code
      run: go generate ./...
    
    - uses: dagger/dagger-for-github@v6
      with:
        verb: call
        module: ./ci
        args: lint --source .

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    
    - name: Generate GraphQL code
      run: go generate ./...
    
    - uses: dagger/dagger-for-github@v6
      with:
        verb: call
        module: ./ci
        args: test --source .

  security-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: dagger/dagger-for-github@v6
      with:
        verb: call
        module: ./ci
        args: security-scan --source .

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ["linux/amd64", "linux/arm64"]
    steps:
    - uses: actions/checkout@v4
    
    - uses: dagger/dagger-for-github@v6
      with:
        verb: call
        module: ./ci
        args: build --source . --platforms ${{ matrix.platform }}

  acceptance-test:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v4
    
    - uses: dagger/dagger-for-github@v6
      with:
        verb: call
        module: ./ci
        args: acceptance-test --source .

  all-checks:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v4
    
    - uses: dagger/dagger-for-github@v6
      with:
        verb: call
        module: ./ci
        args: all --source .