name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release (e.g., v0.1.0)'
        required: true
        type: string

permissions:
  contents: write
  packages: write
  id-token: write # needed for signing with cosign

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.event.inputs.tag || github.ref }}

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        check-latest: true

    - name: Install cosign
      uses: sigstore/cosign-installer@v3

    - name: Install syft
      uses: anchore/sbom-action/download-syft@v0

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_PAT }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        distribution: goreleaser
        version: ~> v2
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        COSIGN_EXPERIMENTAL: 1

  # Keep the existing Dagger publish for additional container registry support
  publish-additional-registries:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Extract version from tag
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
    
    - uses: dagger/dagger-for-github@8.0.0
      with:
        verb: call
        module: ./ci
        args: >-
          publish
          --source .
          --registry docker.io
          --tag ${{ steps.version.outputs.VERSION }}
          --username "${{ secrets.DOCKER_USERNAME }}"
          --password env:DAGGER_DOCKER_PASSWORD
      env:
        DAGGER_DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}